DROP TABLE IF EXISTS t_consult_payment;
DROP TABLE IF EXISTS t_schedule;
DROP TABLE IF EXISTS t_lawyer_payment;
DROP TABLE IF EXISTS t_payment;
DROP TABLE IF EXISTS t_consultation;
DROP TABLE IF EXISTS t_administrator;
DROP TABLE IF EXISTS t_lawyer;
DROP TABLE IF EXISTS t_client;
DROP TABLE IF EXISTS t_lawyer_salary;